const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const f=path.join(root,decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));fs.readFile(f,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':f.endsWith('.js')?'text/javascript':f.endsWith('.html')?'text/html':f.endsWith('.css')?'text/css':'image/png'});res.end(e?'missing':b);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});try{for(const mobile of [false,true]){
 const context=await browser.newContext({viewport:mobile?{width:844,height:390}:{width:1280,height:720},isMobile:mobile,hasTouch:mobile});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>state==='ready',null,{timeout:60000});await page.locator('#start').click();
 const result=await page.evaluate(()=>{const check=(v,m)=>{if(!v)throw Error(m);},step=n=>{for(let i=0;i<n;i++)tick(1/120);};
 const setup=id=>{areaIndex=0;selectedCharacter=id;reset();state='playing';pink.enabled=false;props=[];crates=[];enemies=[];platforms=[];player.x=500;player.inv=100;keys.clear();axis=0;};
 check(new Set(diveArt.nyoro.map(f=>f.sourceId)).size===16,'16 independent Nyoro dive silhouettes');for(const f of diveArt.nyoro){check(f.img.width===f.w&&f.img.height===f.h&&f.x===0&&f.y===0,'isolated dive frame');check(f.sourceHeight===1254,'preserved dive scale reference');}
 for(const id of ['denden','nyoro']){setup(id);startDive();check(!dive,'ground dive forbidden');player.y=250;player.grounded=false;player.coyote=0;startDive();check(dive?.character===id,'air dive starts');const e=spawnGrassEnemy('tank',530);e.stun=100;e.hp=e.maxHP=1000;step(100);check(player.grounded&&!dive,'dive lands and recovers');check(e.hp===1000-DIVE.damage[id]-(id==='nyoro'?2:0),'single landing damage '+id+' '+e.hp);step(70);check(!diveEffects.length,'effects expire');check(diveArt[id].length===16,'16 poses');player.y=250;player.grounded=false;startDive();reset();check(!dive&&!diveEffects.length,'reset clears dive');}
 setup('tetsu');startTetsuAction('combo');tetsuAction.landedAt=0;tetsuAction.age=.11;const x=player.x;step(18);check(player.x>x+20&&player.x<x+40,'finisher advances a little');
 setup('denden');startGiantThunder();giantThunder.landed=true;giantThunder.y=548;let total=0,old=new Set();for(let i=0;i<239;i++){updateGiantThunder(1/120);for(const b of groundBolts)if(!old.has(b)){old.add(b);total++;}}check(total===12,'six bilateral pairs instead of eight '+total);
 for(const area of [0,1]){areaIndex=area;reset();state='playing';pink.enabled=false;props=[];crates=[];enemies=[];const p=platforms.find(p=>p.motion?.axis===(area?'x':'y'));player.x=p.x+p.w/2;player.y=p.y;player.grounded=true;player.vy=0;let drift=0;for(let i=0;i<1440;i++){tick(1/120);drift=Math.max(drift,Math.abs(player.y-p.y),Math.abs(player.x-p.x-p.w/2));}check(drift<.1,'stable moving platform carry '+area+' '+drift);const px=p.x,py=p.y;state='paused';step(100);check(p.x===px&&p.y===py,'platform pause');state='playing';jumpRequest=.13;step(12);check(!player.grounded&&player.y<p.y-10,'jump detaches');}
 areaIndex=2;selectedCharacter='tetsu';reset();state='playing';const rope=ropes[0],end=ropeEnd(rope);player.x=end.x;player.y=end.y+46;player.grounded=false;startTetsuAction('air');updateRopePlayer(1/120,0);check(ropeRide&&!tetsuAction,'rope cancels landing-dependent attack');jumpRequest=.13;updateRopePlayer(1/120,1);check(!ropeRide,'rope release remains available');
 setup('denden');updateCharacterUI();return{diveCharacters:2,bodyFrames:32,effectFrames:16,thunderPairs:6,movingAxes:2};});
 if(mobile)await page.locator('#jump').tap();else await page.keyboard.press('Space');await page.waitForFunction(()=>!player.grounded&&player.y<490);if(mobile)await page.locator('#dive').tap();else await page.keyboard.press('s');await page.waitForFunction(()=>!!dive);await page.waitForFunction(()=>player.grounded&&!dive);
 for(const id of ['denden','nyoro']){await page.evaluate(id=>{resetDive();selectedCharacter=id;player.x=500;player.y=340;camera=100;player.grounded=false;dive={character:id,age:.24,landed:false,dir:1};updateCharacterUI();draw();drawDiveEffects();state='paused';},id);await page.screenshot({path:path.join(process.env.TEMP,`dive-${id}-${mobile}.png`)});}
 assert.deepEqual(errors,[]);console.log(mobile?'MOBILE':'DESKTOP',result);await context.close();}}
 finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
