const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const f=path.join(root,decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));fs.readFile(f,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':f.endsWith('.js')?'text/javascript':f.endsWith('.html')?'text/html':f.endsWith('.css')?'text/css':'image/png'});res.end(e?'missing':b);});});

(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});
try{for(const mobile of [false,true]){
 const context=await browser.newContext({viewport:mobile?{width:844,height:390}:{width:1280,height:720},isMobile:mobile,hasTouch:mobile});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>state==='ready',null,{timeout:120000});
 const result=await page.evaluate(()=>{
 const check=(v,m)=>{if(!v)throw Error(m);},step=n=>{for(let i=0;i<n;i++)tick(1/120);};const layouts=[];
 check(Object.values(newEnemyArt).every(a=>a.length===16),'enemy 16-frame sheets');
 for(let b=0;b<5;b++)for(let a=0;a<4;a++){selectBiome(b);areaIndex=a;reset();state='playing';pink.enabled=false;const types=[...new Set(enemies.filter(e=>NEW_ENEMIES[e.type]).map(e=>e.type))];layouts.push({b,a,types,platforms:platforms.length,props:props.length});check(types.length>0,'random enemies world '+b+' area '+a);check(a===3?!!bossRoom:!bossRoom,'boss only Area 4');step(3);check(Number.isFinite(player.y),'stable spawn');}
 selectBiome(2);reset();state='playing';pink.enabled=false;enemies=[];player.x=1400;player.inv=100;const e=spawnNewEnemy('knife',1700);newEnemyAction(e,'bomb');step(65);check(newEnemyShots.length===1&&newEnemyShots[0].vy<0,'arcing bomb');step(140);check(!newEnemyShots.length,'bomb expires/explodes');player.inv=0;const bombHP=player.hp;newEnemyExplosion(player.x,player.y-30);check(player.hp===bombHP-7,'bomb blast damage');player.inv=100;
 e.x=1600;player.x=1500;newEnemyAction(e,'slash');const kx=e.x;step(65);check(e.x<kx-40,'knife dash slash');
 enemies=[];const n=spawnNewEnemy('naga',1800);player.x=1300;newEnemyAction(n,'dash');const nx=n.x;step(100);check(n.x<nx-150,'naga rush');newEnemyAction(n,'jump');step(55);check(n.y<340,'naga high jump');
 enemies=[];const m=spawnNewEnemy('mag',1800);player.x=1500;newEnemyAction(m,'guard');const hp=m.hp;hitEnemy(m,20,1);check(m.hp===hp-4,'frontal shield');hitEnemy(m,20,-1);check(m.hp===hp-24,'rear bypass');newEnemyAction(m,'slash');step(60);check(newEnemyShots.some(s=>s.kind==='fire'),'fire slash');newEnemyAction(m,'backstep');const mx=m.x;step(40);check(m.x>mx+40,'backstep');
 selectBiome(1);reset();state='playing';pink.enabled=false;enemies=[];const h=sandHills[0];player.x=h.x+h.w/2;player.y=548-h.h;player.vy=0;player.grounded=true;step(120);check(h.gone,'sand collapses');const h2=sandHills[1],random=Math.random;try{Math.random=()=>.1;h2.timer=.71;const count=enemies.length;updateBiome(.02);check(h2.gone&&enemies.length===count+1&&enemies.at(-1).dropping,'sand ejects enemy');}finally{Math.random=random;}
 const prop=props[0];damageBiomeProp(prop,999);check(prop.death===0&&prop.hp===0,'destruction');
 selectBiome(2);reset();state='playing';pink.enabled=false;const tire=townTires[0];player.x=tire.x-300;const tx=tire.x;step(60);check(tire.x<tx,'rolling tire');
 selectBiome(3);reset();state='playing';pink.enabled=false;check(platforms.filter(p=>p.motion).length>=6,'many moving neon ledges');const p=platforms.find(p=>p.motion?.axis==='y');player.x=p.x+p.w/2;player.y=p.y;player.grounded=true;const py=p.y;step(40);check(p.y!==py&&Math.abs(player.y-p.y)<1,'moving platform carries player');
 selectBiome(4);reset();state='playing';pink.enabled=false;check(platforms.some(p=>p.geyser)&&gaps.every(g=>g.lava),'magma geyser and pits');player.x=gaps[0].x+20;player.y=600;const ph=player.hp;step(1);check(player.x===checkpoint.x&&player.hp<ph,'lava respawn');
 selectBiome(2);areaIndex=3;reset();state='playing';pink.enabled=false;bossRoom.state='cleared';player.x=CONFIG.worldWidth-179;finishGrassArea();check(state==='clear'&&!document.getElementById('next-biome').hidden,'world clear');document.getElementById('next-biome').click();check(biomeIndex===3&&areaIndex===0&&state==='playing','next world');
 return {layouts,sheets:Object.keys(newEnemyArt).length,props:true,gimmicks:true,enemyCombat:true,nextWorld:true};});
 console.log(mobile?'MOBILE':'DESKTOP',JSON.stringify(result));
 await page.evaluate(()=>{state='ready';document.getElementById('overlay').hidden=false;document.getElementById('character-select').hidden=false;});
 await page.evaluate(()=>{state='areaClear';areaIndex=2;});await page.locator('[data-biome="2"]').click();await page.locator('#start').click();assert.equal(await page.evaluate(()=>biomeIndex),2);assert.equal(await page.evaluate(()=>areaIndex),0);
 if(mobile){const client=await context.newCDPSession(page),zone=await page.locator('#stick-zone').boundingBox(),shoot=await page.locator('#shoot').boundingBox(),jump=await page.locator('#jump').boundingBox();const finger=(id,x,y)=>({id,x,y,radiusX:3,radiusY:3,force:1}),a=finger(0,zone.x+zone.width*.4,zone.y+zone.height*.5),b=finger(1,shoot.x+shoot.width/2,shoot.y+shoot.height/2),c=finger(2,jump.x+jump.width/2,jump.y+jump.height/2);
 await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[a]});a.x+=40;await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[a]});await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[a,b,c]});await page.waitForTimeout(180);const input=await page.evaluate(()=>({x:player.x,y:player.y,running,shots:bullets.length,scroll:scrollY}));assert(input.x>155&&input.y<530&&input.running&&input.shots>0&&input.scroll===0,JSON.stringify(input));await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});console.log('MULTITOUCH move + jump + shoot OK');}

 for(let b=1;b<5;b++){await page.evaluate(b=>{selectBiome(b);reset();state='playing';player.inv=100;player.x=1250;camera=850;document.getElementById('overlay').hidden=true;for(let i=0;i<3;i++)tick(1/120);draw();drawNewEnemyProjectiles();state='paused';},b);await page.screenshot({path:path.join(root,'tests/expansion-'+b+'-'+mobile+'.png')});}
 assert.deepEqual(errors,[]);await context.close();}
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
