// npm install --no-save playwright, then: node tests/game.test.cjs
const {chromium}=require('playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png'})[path.extname(file)]||'text/plain'});res.end(e?'Not found':b);});});
async function main(){await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});const failures=[];
try{for(const mobile of [false,true]){const context=await browser.newContext({viewport:mobile?{width:844,height:390}:{width:1280,height:720},isMobile:mobile,hasTouch:mobile,deviceScaleFactor:mobile?2:1});const page=await context.newPage();page.on('pageerror',e=>failures.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>state==='ready');await page.locator('#start').click();
if(!mobile){await page.keyboard.down('KeyD');await page.waitForTimeout(350);await page.keyboard.up('KeyD');console.log(await page.evaluate(()=>({state,x:player.x,elapsed,vx:player.vx,keys:[...keys]})));assert(await page.evaluate(()=>player.x>150));await page.keyboard.down('KeyA');await page.waitForTimeout(200);await page.keyboard.up('KeyA');assert.equal(await page.evaluate(()=>player.dir),-1);await page.keyboard.down('Shift');await page.keyboard.down('KeyD');await page.keyboard.down('Space');await page.keyboard.down('KeyJ');await page.waitForTimeout(180);assert(await page.evaluate(()=>!player.grounded&&running&&bullets.length>0));await page.keyboard.up('Space');await page.keyboard.up('KeyJ');await page.keyboard.up('KeyD');await page.keyboard.up('Shift');}
else{const cd=await context.newCDPSession(page);const box=await page.locator('#stick-zone').boundingBox(),jump=await page.locator('#jump').boundingBox(),shoot=await page.locator('#shoot').boundingBox();const origin={x:box.x+box.width*.45,y:box.y+box.height*.55},radius=844*.044;const point=(id,x,y)=>({id,x,y,radiusX:5,radiusY:5,force:1});const send=(type,points)=>cd.send('Input.dispatchTouchEvent',{type,touchPoints:points});await send('touchStart',[point(1,origin.x,origin.y)]);await send('touchMove',[point(1,origin.x+radius*.55,origin.y)]);await page.waitForTimeout(120);assert(await page.evaluate(()=>player.vx===CONFIG.walkSpeed&&!running));await send('touchMove',[point(1,origin.x+radius*.95,origin.y)]);await page.waitForTimeout(100);assert(await page.evaluate(()=>running&&player.vx===CONFIG.dashSpeed));await send('touchStart',[point(1,origin.x+radius*.95,origin.y),point(2,jump.x+jump.width/2,jump.y+jump.height/2),point(3,shoot.x+shoot.width/2,shoot.y+shoot.height/2)]);await page.waitForTimeout(170);assert(await page.evaluate(()=>!player.grounded&&bullets.length>0&&running));await send('touchEnd',[]);await page.waitForTimeout(70);assert(await page.evaluate(()=>axis===0&&pointers.shoot.size===0&&pointers.jump.size===0));await send('touchStart',[point(1,origin.x,origin.y)]);await send('touchMove',[point(1,origin.x-radius*.55,origin.y)]);await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>player.dir),-1);await send('touchCancel',[]);assert(await page.evaluate(()=>axis===0));assert.equal(await page.evaluate(()=>window.scrollY),0);}
// Deterministic physics checks run the actual game update with the actual stage.
const result=await page.evaluate(()=>{
  const check=(v,msg)=>{if(!v)throw Error(msg);};const step=n=>{for(let i=0;i<n;i++)tick(1/120);};reset();state='playing';
  axis=.55;step(12);check(player.vx===CONFIG.walkSpeed,'walk');axis=.9;step(12);check(running,'dash');axis=.7;step(12);check(running,'dash hysteresis');axis=.6;step(12);check(!running,'walk hysteresis');axis=0;step(12);
  player.x=900;player.y=490;player.grounded=true;for(let i=0;i<120;i++)tick(1/120);check(player.y===490&&player.grounded,'stable platform');jumpRequest=CONFIG.jumpBuffer;step(1);check(player.vy<0,'platform jump');step(110);check(player.y===490,'platform landing');
  reset();state='playing';player.x=1400;keys.add('KeyJ');step(90);check(kills>=1,'enemy death');check(particles.length<=250,'effect bound');keys.clear();step(250);check(bullets.length===0,'bullet cleanup');
  reset();state='playing';const e=enemies[0];player.x=e.x;step(1);const hp=player.hp;check(hp<50&&player.inv>0&&player.red>0,'contact damage');step(6);check(player.hp===hp,'invincibility');
  reset();state='playing';player.x=380;step(1);check(collected===1&&popups.length===1,'coin pickup');step(100);check(popups.length===0,'coin effect cleanup');
  reset();state='playing';keys.add('KeyD');keys.add('ShiftLeft');keys.add('KeyJ');let jumped=0,maxBullets=0;for(let i=0;i<120*120&&state==='playing';i++){const obstacle=platforms.find(q=>q.solid&&q.x-player.x>0&&q.x-player.x<125);if(player.grounded&&(obstacle||i%180===0)){jumpRequest=CONFIG.jumpBuffer;jumped++;}tick(1/120);maxBullets=Math.max(maxBullets,bullets.length);}check(state==='clear','full route: '+state+' at '+player.x);check(elapsed>=60&&elapsed<120,'duration');check(camera>19000,'camera');check(collected>10,'route coins');check(kills>15,'route combat');check(maxBullets<15,'bounded bullets');const summary={seconds:elapsed,coins:collected,kills,hp:player.hp,jumps:jumped,maxBullets};return summary;
});
console.log(mobile?'MOBILE landscape + real multi-touch':'DESKTOP keyboard',JSON.stringify(result));await page.screenshot({path:path.join(process.env.TEMP||root,mobile?'mob-mobile-clear.png':'mob-desktop-clear.png')});await page.locator('#start').click();assert(await page.evaluate(()=>state==='playing'&&player.hp===50&&collected===0&&kills===0&&player.x<150));await page.evaluate(()=>{player.x=3200;camera=2800;});await page.screenshot({path:path.join(process.env.TEMP||root,mobile?'mob-mobile.png':'mob-desktop.png')});
await page.evaluate(()=>{player.hp=1;player.x=enemies[0].x;tick(1/120);});assert.equal(await page.evaluate(()=>state),'dead');await page.locator('#start').click();await page.locator('#pause').click();assert.equal(await page.evaluate(()=>state),'paused');await page.locator('#start').click();assert.equal(await page.evaluate(()=>state),'playing');if(mobile){await page.setViewportSize({width:390,height:844});await page.waitForTimeout(100);assert(await page.locator('#rotate').isVisible());assert.equal(await page.evaluate(()=>state),'paused');await page.setViewportSize({width:844,height:390});await page.waitForTimeout(100);assert(!(await page.locator('#rotate').isVisible()));}await context.close();}
assert.deepEqual(failures,[]);console.log('PASS: movement, hysteresis, jump, air shooting, multitouch, platform landing, combat, damage, coins, camera, clear, retry, game over, pause, portrait guard, no page errors.');}finally{await browser.close();server.close();}}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
