// npm install --no-save playwright, then: node tests/game.test.cjs
const {chromium}=require('playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png'})[path.extname(file)]||'text/plain'});res.end(e?'Not found':b);});});
async function main(){await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});const failures=[];
try{for(const mobile of [false,true]){const context=await browser.newContext({viewport:mobile?{width:844,height:390}:{width:1280,height:720},isMobile:mobile,hasTouch:mobile,deviceScaleFactor:mobile?2:1});const page=await context.newPage();page.on('pageerror',e=>failures.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>state==='ready');await page.locator('#start').click();
if(!mobile){await page.keyboard.down('KeyD');await page.waitForFunction(()=>player.x>180);await page.keyboard.up('KeyD');assert(await page.evaluate(()=>player.x>180));await page.keyboard.down('KeyA');await page.waitForTimeout(200);await page.keyboard.up('KeyA');assert.equal(await page.evaluate(()=>player.dir),-1);await page.keyboard.down('Shift');await page.keyboard.down('KeyD');await page.keyboard.down('Space');await page.keyboard.down('KeyJ');await page.waitForTimeout(180);assert(await page.evaluate(()=>!player.grounded&&running&&bullets.length>0));await page.keyboard.up('Space');await page.keyboard.up('KeyJ');await page.keyboard.up('KeyD');await page.keyboard.up('Shift');
await page.keyboard.down('Digit1');await page.waitForFunction(()=>skillState.charge>.15);assert(await page.evaluate(()=>skillState.charging&&playerImage()===skillSprites[Math.floor(player.anim*12)%8]));await page.keyboard.up('Digit1');assert(await page.evaluate(()=>!skillState.charging&&energyShots.length===1&&skillState.cooldowns[0]>7));await page.keyboard.press('Digit2');assert(await page.evaluate(()=>skillState.thunderLeft>2&&skillState.cooldowns[1]>11));}
else{const cd=await context.newCDPSession(page);const box=await page.locator('#stick-zone').boundingBox(),jump=await page.locator('#jump').boundingBox(),shoot=await page.locator('#shoot').boundingBox();const origin={x:box.x+box.width*.45,y:box.y+box.height*.55},radius=844*.044;const point=(id,x,y)=>({id,x,y,radiusX:5,radiusY:5,force:1});const send=(type,points)=>cd.send('Input.dispatchTouchEvent',{type,touchPoints:points});await send('touchStart',[point(1,origin.x,origin.y)]);await send('touchMove',[point(1,origin.x+radius*.55,origin.y)]);await page.waitForTimeout(120);assert(await page.evaluate(()=>player.vx===CONFIG.walkSpeed&&!running));await send('touchMove',[point(1,origin.x+radius*.95,origin.y)]);await page.waitForTimeout(100);assert(await page.evaluate(()=>running&&player.vx===CONFIG.dashSpeed));await send('touchStart',[point(1,origin.x+radius*.95,origin.y),point(2,jump.x+jump.width/2,jump.y+jump.height/2),point(3,shoot.x+shoot.width/2,shoot.y+shoot.height/2)]);await page.waitForTimeout(170);assert(await page.evaluate(()=>!player.grounded&&bullets.length>0&&running));await send('touchEnd',[]);await page.waitForTimeout(70);assert(await page.evaluate(()=>axis===0&&pointers.shoot.size===0&&pointers.jump.size===0));await send('touchStart',[point(1,origin.x,origin.y)]);await send('touchMove',[point(1,origin.x-radius*.55,origin.y)]);await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>player.dir),-1);await send('touchCancel',[]);assert(await page.evaluate(()=>axis===0));assert.equal(await page.evaluate(()=>window.scrollY),0);}
if(mobile){await page.evaluate(()=>{reset();state='playing';});const cd=await context.newCDPSession(page),stick=await page.locator('#stick-zone').boundingBox(),skill=await page.locator('[data-skill="0"]').boundingBox(),jump=await page.locator('#jump').boundingBox();const p=(id,x,y)=>({id,x,y,radiusX:4,radiusY:4,force:1});const a=p(1,stick.x+70,stick.y+50),b=p(2,skill.x+skill.width/2,skill.y+skill.height/2),c=p(3,jump.x+jump.width/2,jump.y+jump.height/2);await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[a,b]});await cd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...a,x:a.x+40},b]});await page.waitForFunction(()=>skillState.charge>.1&&running);await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...a,x:a.x+40},b,c]});await page.waitForFunction(()=>!player.grounded&&skillState.charging);await cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[b]});assert(await page.evaluate(()=>energyShots.length===1&&!skillState.charging&&axis>0));await cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.evaluate(()=>{reset();state='playing';});await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[b]});await cd.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});assert(await page.evaluate(()=>!skillState.charging&&energyShots.length===0&&skillState.cooldowns[0]===0));await page.locator('[data-skill="1"]').tap();assert(await page.evaluate(()=>skillState.thunderLeft>2));}
const skillResult=await page.evaluate(()=>{
  const check=(v,msg)=>{if(!v)throw Error(msg);},step=n=>{for(let i=0;i<n;i++)tick(1/120);};reset();state='playing';beginCharge('test');step(420);check(skillState.charge===3,'charge capped at 3s');check(energyShots.length===0,'hold must not auto fire');endCharge('test',true);check(energyShots[0].damage===CONFIG.bulletDamage*10,'full charge 1000%');check(skillState.cooldowns[0]===8,'8s cooldown');beginCharge('blocked');check(!skillState.charging,'cooldown blocks skill');step(961);check(skillState.cooldowns[0]===0,'cooldown ready');
  beginCharge('tap');endCharge('tap',true);check(energyShots[0].damage===CONFIG.bulletDamage*3,'tap 300%');
  reset();state='playing';beginCharge('half');step(180);endCharge('half',true);check(Math.abs(energyShots[0].damage-CONFIG.bulletDamage*6.5)<.001,'linear charge multiplier');
  const first=enemies[0],second=enemies[1];enemies=[first,second];for(const [i,e] of enemies.entries()){e.x=e.home=player.x+190+i*65;e.hp=e.maxHP=1000;e.range=0;}const damage=energyShots[0].damage;step(35);check(Math.abs(first.hp-(1000-damage))<.001,'direct damage once');check(Math.abs(second.hp-(1000-damage*.5))<.001,'splash half damage once');check(explosions.length===1,'impact explosion');step(80);check(explosions.length===0&&energyShots.length===0,'skill effect cleanup');
  reset();state='playing';player.dir=-1;beginCharge('left');endCharge('left',true);check(energyShots[0].dir===-1,'left skill');
  reset();state='playing';const target=enemies[0];target.hp=target.maxHP=1000;enemies=[target];lightning.push({x:target.x,y:target.y-target.h-5,life:.55,hit:new Set()});step(10);check(target.hp===940,'one lightning is 500%, once per enemy');
  reset();state='playing';castThunder();check(skillState.cooldowns[1]===12,'12s thunder cooldown');step(120);const previous=skillState.thunderLeft;castThunder();check(skillState.thunderLeft===previous,'no thunder recast');step(241);check(skillState.thunderLeft===0&&lightning.length===0,'thunder finishes in 3s');step(1200);check(skillState.cooldowns[1]===0,'thunder cooldown expires');
  CONFIG.skills.trick.cooldownReduction=100;CONFIG.skills.thunder.cooldownReduction=100;check(skillCooldown('trick')===5&&skillCooldown('thunder')===9,'upgrade cooldown floor');CONFIG.skills.trick.cooldownReduction=0;CONFIG.skills.thunder.cooldownReduction=0;
  beginCharge('pause');step(30);pause();endCharge('pause',true);check(energyShots.length===0&&!skillState.charging,'pause cancels charge without firing');resume();reset();check(energyShots.length===0&&lightning.length===0&&skillState.cooldowns.every(c=>c===0),'retry resets all skills');
  reset();state='playing';jumpRequest=CONFIG.jumpBuffer;step(20);check(player.jumpsUsed===1&&!player.grounded,'first jump');jumpRequest=CONFIG.jumpBuffer;step(1);check(player.jumpsUsed===2&&player.vy< -600,'second jump');step(10);const beforeThird=player.vy;jumpRequest=CONFIG.jumpBuffer;step(1);check(player.jumpsUsed===2&&player.vy>beforeThird,'no third jump');step(150);check(player.grounded&&player.jumpsUsed===0,'landing restores jumps');
  reset();state='playing';beginCharge('geometry');step(361);const g=energyChargeGeometry(),phase=player.anim;check(g.x>player.x&&g.y===player.y-47&&g.r===58,'muzzle position and larger charge');endCharge('geometry',true);check(energyShots[0].r===g.r&&energyShots[0].x===g.x&&energyShots[0].y===g.y&&energyShots[0].visualAge===phase,'release preserves size position and frame');step(10);check(energyShots[0].r===58,'projectile never shrinks');
  reset();state='playing';keys.add('KeyD');castThunder();const lockedX=player.x;step(120);jumpRequest=CONFIG.jumpBuffer;step(119);check(player.x===lockedX&&player.grounded&&skillSprites.slice(24).includes(playerImage()),'two-second animation movement and jump lock');step(4);check(player.x>lockedX&&!thunderLocked(),'unlock after two seconds');
  reset();state='playing';castThunder();const positions=[],times=[];let priorWave=0;for(let i=0;i<300;i++){tick(1/120);if(skillState.wave!==priorWave){priorWave=skillState.wave;positions.push(lightning[lightning.length-1].x);times.push(i);}}check(positions.length>20&&new Set(times.slice(1).map((t,i)=>t-times[i])).size>1,'random timing');check(positions.some((x,i)=>i&&x<positions[i-1])&&positions.some((x,i)=>i&&x>positions[i-1]),'random positions and order');
  reset();state='playing';return {charge:'muzzle / 58px radius / preserved at release',jump:'double jump; third blocked',thunder:'2s lock / randomized rain',cooldowns:'8s / 12s; minimum 5s / 9s'};
});console.log('SKILLS',JSON.stringify(skillResult));
await page.evaluate(()=>{reset();state='playing';player.x=3200;camera=2800;beginCharge('visual');for(let i=0;i<360;i++)tick(1/120);state='paused';});await page.screenshot({path:path.join(process.env.TEMP||root,mobile?'mob-mobile-charge.png':'mob-desktop-charge.png')});
await page.evaluate(()=>{reset();state='playing';player.x=3200;camera=2800;castThunder();for(let i=0;i<32;i++)tick(1/120);state='paused';});await page.screenshot({path:path.join(process.env.TEMP||root,mobile?'mob-mobile-thunder.png':'mob-desktop-thunder.png')});
// Deterministic physics checks run the actual game update with the actual stage.
const result=await page.evaluate(()=>{
  const check=(v,msg)=>{if(!v)throw Error(msg);};const step=n=>{for(let i=0;i<n;i++)tick(1/120);};reset();state='playing';
  axis=.55;step(12);check(player.vx===CONFIG.walkSpeed,'walk');axis=.9;step(12);check(running,'dash');axis=.7;step(12);check(running,'dash hysteresis');axis=.6;step(12);check(!running,'walk hysteresis');axis=0;step(12);
  player.x=900;player.y=490;player.grounded=true;for(let i=0;i<120;i++)tick(1/120);check(player.y===490&&player.grounded,'stable platform');jumpRequest=CONFIG.jumpBuffer;step(1);check(player.vy<0,'platform jump');step(110);check(player.y===490,'platform landing');
  reset();state='playing';player.x=1400;keys.add('KeyJ');step(90);check(kills>=1,'enemy death');check(particles.length<=250,'effect bound');keys.clear();step(250);check(bullets.length===0,'bullet cleanup');
  reset();state='playing';const e=enemies[0];player.x=e.x;step(1);const hp=player.hp;check(hp<50&&player.inv>0&&player.red>0,'contact damage');step(6);check(player.hp===hp,'invincibility');
  reset();state='playing';player.x=380;step(1);check(collected===1&&popups.length===1,'coin pickup');step(100);check(popups.length===0,'coin effect cleanup');
  reset();state='playing';keys.add('KeyD');keys.add('ShiftLeft');keys.add('KeyJ');let jumped=0,maxBullets=0;for(let i=0;i<120*120&&state==='playing';i++){const obstacle=platforms.find(q=>q.solid&&q.x-player.x>0&&q.x-player.x<125);if(player.grounded&&(obstacle||i%180===0)){jumpRequest=CONFIG.jumpBuffer;jumped++;}tick(1/120);maxBullets=Math.max(maxBullets,bullets.length);}check(state==='clear','full route: '+state+' at '+player.x);check(elapsed>=60&&elapsed<120,'duration');check(camera>19000,'camera');check(collected>10,'route coins');check(kills>15,'route combat');check(maxBullets<15,'bounded bullets');const summary={seconds:elapsed,coins:collected,kills,hp:player.hp,jumps:jumped,maxBullets};return summary;
});
const skillRoute=await page.evaluate(()=>{reset();state='playing';keys.add('KeyD');keys.add('ShiftLeft');keys.add('KeyJ');let casts=0,storms=0,maxLightning=0;for(let i=0;i<14400&&state==='playing';i++){if(player.grounded&&(platforms.some(q=>q.solid&&q.x-player.x>0&&q.x-player.x<125)||i%180===0))jumpRequest=CONFIG.jumpBuffer;if(skillState.cooldowns[0]===0&&!skillState.charging)beginCharge('route');if(skillState.charge===3){endCharge('route',true);casts++;}if(skillState.cooldowns[1]===0){castThunder();storms++;}tick(1/120);maxLightning=Math.max(maxLightning,lightning.length);}if(state!=='clear'||casts<4||storms<4||maxLightning>27)throw Error('skill route failed');return{seconds:elapsed,casts,storms,maxLightning,hp:player.hp};});
console.log('SKILL ROUTE',JSON.stringify(skillRoute));console.log(mobile?'MOBILE landscape + real multi-touch':'DESKTOP keyboard',JSON.stringify(result));await page.screenshot({path:path.join(process.env.TEMP||root,mobile?'mob-mobile-clear.png':'mob-desktop-clear.png')});await page.locator('#start').click();assert(await page.evaluate(()=>state==='playing'&&player.hp===50&&collected===0&&kills===0&&player.x<150));await page.evaluate(()=>{player.x=3200;camera=2800;});await page.screenshot({path:path.join(process.env.TEMP||root,mobile?'mob-mobile.png':'mob-desktop.png')});
await page.evaluate(()=>{reset();state='playing';player.hp=1;player.x=enemies[0].x;tick(1/120);});assert.equal(await page.evaluate(()=>state),'dead');await page.locator('#start').click();await page.locator('#pause').click();assert.equal(await page.evaluate(()=>state),'paused');await page.locator('#start').click();assert.equal(await page.evaluate(()=>state),'playing');if(mobile){await page.setViewportSize({width:390,height:844});await page.waitForTimeout(100);assert(await page.locator('#rotate').isVisible());assert.equal(await page.evaluate(()=>state),'paused');await page.setViewportSize({width:844,height:390});await page.waitForTimeout(100);assert(!(await page.locator('#rotate').isVisible()));}await context.close();}
assert.deepEqual(failures,[]);console.log('PASS: movement, hysteresis, jump, air shooting, multitouch, platform landing, combat, damage, coins, camera, clear, retry, game over, pause, portrait guard, no page errors.');}finally{await browser.close();server.close();}}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
