// npm install --no-save playwright, then: node tests/game.test.cjs
const {chromium}=require('playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png'})[path.extname(file)]||'text/plain'});res.end(e?'Not found':b);});});
async function main(){await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});try{for(const mobile of [false,true]){
 const context=await browser.newContext({viewport:mobile?{width:844,height:390}:{width:1280,height:720},isMobile:mobile,hasTouch:mobile}),page=await context.newPage(),errors=[];page.setDefaultNavigationTimeout(90000);page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>state==='ready');await page.locator('#start').click();
 await page.evaluate(()=>{state='ready';document.getElementById('overlay').hidden=false;});
 assert(await page.locator('[data-character="miramob"]').isHidden());await page.locator('#title-settings summary').click();await page.locator('#admin-code').fill('1111');await page.locator('#admin-form button').click();assert(await page.locator('[data-character="miramob"]').isHidden());await page.locator('#admin-code').pressSequentially('0329');await page.locator('#admin-form button').click();await page.locator('[data-character="miramob"]').click();assert.equal(await page.evaluate(()=>selectedCharacter),'miramob');await page.locator('#start').click();
 if(mobile)await page.locator('#shoot').tap();else await page.keyboard.press('j');await page.waitForFunction(()=>miraAction?.type==='normal');
 const result=await page.evaluate(()=>{
  const check=(v,m)=>{if(!v)throw Error(m);},step=n=>{for(let i=0;i<n;i++)tick(1/120);};
  const setup=(character='denden')=>{selectedCharacter=character;reset();state='playing';pink.enabled=false;player.x=500;platforms=[];crates=[];enemies=[];};
  const enemy=(x)=>{const e={type:'tank',x,y:548,home:x,dir:-1,hp:1000,maxHP:1000,w:62,h:65,flash:0,knock:0,death:-1,range:0,phase:0,stun:100};enemies.push(e);return e;};
  setup();pink.enabled=true;pink.x=430;const p0=pink.y;jumpRequest=.13;step(1);check(pink.grounded&&pink.y===p0,'Pink does not mirror player jump');enemy(565);pink.magicCooldown=0;step(31);check(anomaBursts.length===1&&enemies[0].hp===980&&enemies[0].launch.spin===14,'Anoma hits and spins enemy upward');step(120);check(!pink.magic&&!anomaBursts.length,'Anoma ends');
  setup('tetsu');player.dir=-1;enemy(700);castTetsu(1);check(tetsuAction.dir===-1&&player.dir===-1,'dash retains facing despite enemy to right');step(40);check(player.x<350,'dash goes left');
  setup();const center=enemy(710),left=enemy(460),right=enemy(960);castThunder();step(20);check(giantThunder&&!giantThunder.landed&&center.hp===1000,'large lightning descends');step(45);check(giantThunder.landed&&center.hp<=940&&center.stun>0&&groundBolts.some(b=>b.dir===-1)&&groundBolts.some(b=>b.dir===1),'impact damage stun and both wave directions');step(95);check(left.hp<1000&&right.hp<1000,'ground lightning travels left and right');const age=giantThunder.groundAge;pause();step(120);check(giantThunder.groundAge===age,'lightning pauses');resume();step(160);check(!giantThunder&&!groundBolts.length&&!lightning.length,'two seconds then expires without old rain');
  setup('miramob');const close=enemy(640);miraAttack();step(23);check(close.hp===976&&miraEffects.some(e=>e.kind==='claw'),'fast claw reaches beyond sprite');step(60);check(!miraAction,'normal ends');
  setup('miramob');castMira(0);step(90);check(miraShots.length===4&&miraShots.every(s=>s.kind==='blade'),'four wavering shots');step(400);check(miraShots.length===0,'shots expire');
  setup('miramob');const hit=enemy(650);castMira(0);step(55);check(hit.hp<1000&&hit.purple>0&&miraEffects.some(e=>e.kind==='slash'),'purple hit and slash effect');
  setup('miramob');const coreTarget=enemy(640);castMira(1);step(250);check(!miraShots.length&&miraAction?.type==='skull','two second charge');step(35);check(miraShots.some(s=>s.kind==='core')&&coreTarget.hp<1000&&!miraEffects.some(e=>e.kind==='skull'),'core pierces without early detonation');step(105);check(miraEffects.some(e=>e.kind==='skull')&&miraShots.some(s=>s.kind==='shard'),'timed explosion releases shards');check(coreTarget.hp<=900,'explosion damage');step(160);check(!miraShots.length&&!miraEffects.length,'skull effects cleanup');
  setup('miramob');const shardTarget=enemy(1000);explodeSkull({x:700,y:515,dir:1,hostile:false});check(shardTarget.hp===1000,'outside main skull explosion');step(110);check(shardTarget.hp===986,'outward small skull deals its own damage');
  setup();player.inv=0;const hp=player.hp;miraDamage(player,MIRA.bossExplosion,1,true,true);check(player.hp===hp-12&&player.purple>0,'boss attack damages player with purple flash');
  selectedCharacter='denden';reset();pink.enabled=false;state='playing';check(platforms.filter(p=>p.bossPlatform).length===2&&platforms.filter(p=>p.x>bossRoom.x).every(p=>p.bossPlatform),'boss room has only two ledges');check(bossRoom.right-bossRoom.x>arenas[0].right-arenas[0].x,'boss room wider than ordinary arena');player.x=bossRoom.x+170;step(1);check(bossRoom.state==='closing'&&bossRoom.boss.hp===960,'boss entrance');step(100);const cam=camera;player.inv=100;keys.add('KeyA');step(120);check(player.x>=bossRoom.x+96&&camera===cam,'left gate and camera lock');keys.clear();player.x=bossRoom.right-96;keys.add('KeyD');step(60);check(player.x<=bossRoom.right-96&&state==='playing','right gate blocks goal');keys.clear();bossRoom.spawnClock=.01;step(2);check(enemies.some(e=>e.bossAdd&&e.dropping),'mummy drops from sky');
  bossRoom.boss.stun=0;bossRoom.boss.action=null;bossRoom.boss.skillCD=[0,0];step(1);check(bossRoom.boss.action?.type==='skull','boss autonomously charges skill');const frozen=bossRoom.boss.action.age;pause();step(100);check(bossRoom.boss.action.age===frozen,'boss pauses');resume();step(410);check(miraEffects.some(e=>e.kind==='skull')||miraShots.some(s=>s.hostile),'boss releases hostile attack');hitEnemy(bossRoom.boss,9999);step(140);check(bossRoom.state==='cleared'&&!miraShots.some(s=>s.hostile)&&!enemies.some(e=>e.bossAdd&&e.death<0),'boss defeat opens rocks and clears adds');player.x=CONFIG.worldWidth-179;step(1);check(state==='clear','goal only after boss defeat');reset();check(bossRoom.state==='idle'&&!miraShots.length&&!miraAction,'retry resets boss');
  return {pink:'Anoma / independent jump',thunder:'one large strike + 2s ground waves',mira:'admin / claws / four shots / timed skull',boss:'locked room / two platforms / sparse adds / defeat unlock'};
 });console.log(mobile?'MOBILE':'DESKTOP',result);await page.evaluate(()=>{selectedCharacter='miramob';reset();state='playing';document.getElementById('overlay').hidden=true;player.x=bossRoom.x+260;for(let i=0;i<100;i++)tick(1/120);castMira(1);for(let i=0;i<200;i++)tick(1/120);state='paused';draw();drawSkills();drawMiraEffects();drawBossRoom();});await page.screenshot({path:path.join(process.env.TEMP,`miramob-boss-${mobile}.png`)});assert.deepEqual(errors,[]);await context.close();
 }}finally{await browser.close();server.close();}}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
