const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const f=path.join(root,decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));fs.readFile(f,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':f.endsWith('.js')?'text/javascript':f.endsWith('.html')?'text/html':f.endsWith('.css')?'text/css':'image/png'});res.end(e?'missing':b);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});try{for(const mobile of [false,true]){
 const context=await browser.newContext({viewport:mobile?{width:844,height:390}:{width:1280,height:720},isMobile:mobile,hasTouch:mobile}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>state==='ready',null,{timeout:60000});await page.locator('#start').click();
 const result=await page.evaluate(()=>{const check=(v,m)=>{if(!v)throw Error(m);},step=n=>{for(let i=0;i<n;i++)tick(1/120);};
 const setup=dir=>{selectedCharacter='nyoro';areaIndex=0;reset();state='playing';pink.enabled=false;props=[];crates=[];enemies=[];platforms=[];player.x=1000;player.dir=dir;player.inv=100;keys.clear();axis=0;};
 check(nyoroComboArt.body.length===16&&nyoroComboArt.effects.length===16,'both 4x4 sheets loaded');
 check(new Set(nyoroComboArt.body.map(f=>f.sourceId)).size===16,'one distinct silhouette per frame');
 for(const f of nyoroComboArt.body){check(Math.abs(f.scale*f.faceWidth-35)<.001,'consistent adjusted body scale');check(f.img.width===f.w&&f.img.height===f.h&&f.x===0&&f.y===0,'isolated frame canvas');check(f.w<400&&f.h<350,'no adjacent body in frame');}
 for(const dir of [1,-1]){setup(dir);const e=spawnGrassEnemy('tank',player.x+dir*75),front=spawnGrassEnemy('tank',player.x+dir*420);for(const t of [e,front]){t.hp=t.maxHP=1000;t.stun=100;}nyoroAttack();nyoroAttack();let action=null;const shots=new Set();for(let i=0;i<330;i++){tick(1/120);if(nyoroAction?.type==='followup')action=nyoroAction;for(const b of nyoroOrbs){shots.add(b);if(b.up)check(b.vy<0||b.age>.1,'upward launch');else check(b.vy===0,'forward shot remains horizontal');}draw();drawNyoroEffects();}check(action?.hit.get('sweep')?.has(e),'upper target hit by projectile '+dir);check(action?.hit.get('burst')?.size===1,'forward enemy hit '+dir);check(action.orbUp&&action.orbForward&&shots.size<=2,'both shots emitted without repeats');check(e.hp+front.hp<=1902&&e.hp+front.hp>=1886,'each projectile damages once '+(e.hp+front.hp));check(!nyoroAction&&!nyoroOrbs.length&&!nyoroOrbHits.length,'recovery and cleanup');}

 setup(1);const frontOnly=spawnGrassEnemy('tank',1260);frontOnly.stun=100;frontOnly.hp=1000;const forwardAction={dir:1,hit:new Map()};spawnNyoroOrb(forwardAction,false);check(frontOnly.hp===1000,'no damage before projectile arrival');step(90);check(forwardAction.hit.get('burst')?.has(frontOnly)&&frontOnly.hp<=968,'forward projectile travels and hits');
 setup(1);nyoroAttack();step(65);check(!nyoroAction,'single tap does not auto combo');nyoroCombo=.2;nyoroAttack();step(80);check(nyoroAction?.type==='followup','upper chains');const age=nyoroAction.age;pause();step(100);check(nyoroAction.age===age,'pause');resume();reset();check(!nyoroAction&&!nyoroOrbs.length&&!nyoroOrbHits.length,'retry clears');
 setup(1);updateCharacterUI();return{bodyFrames:16,effectFrames:16,directions:2,hits:4};});
 if(mobile){await page.locator('#shoot').tap();await page.locator('#shoot').tap();}else{await page.keyboard.press('j');await page.keyboard.press('j');}await page.waitForFunction(()=>nyoroAction?.type==='followup'&&nyoroAction.age>.20&&nyoroOrbs.length>0);await page.screenshot({path:path.join(process.env.TEMP,`nyoro-combo-${mobile}.png`)});await page.waitForFunction(()=>!nyoroAction);assert.deepEqual(errors,[]);console.log(mobile?'MOBILE':'DESKTOP',result);await context.close();}}
 finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
