// npm install --no-save playwright, then: node tests/game.test.cjs
const {chromium}=require('playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png'})[path.extname(file)]||'text/plain'});res.end(e?'Not found':b);});});
async function main(){await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});try{for(const mobile of [false,true]){
 const context=await browser.newContext({viewport:mobile?{width:844,height:390}:{width:1280,height:720},isMobile:mobile,hasTouch:mobile}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>state==='ready');await page.locator('#start').click();
 await page.evaluate(()=>{state='ready';});await page.locator('[data-character="nyoro"]').evaluate(b=>b.click());await page.evaluate(()=>{state='playing';});
 if(mobile)await page.locator('#jump').tap();else await page.keyboard.press('Space');await page.waitForFunction(()=>!player.grounded);if(mobile)await page.locator('#jump').tap();else await page.keyboard.press('Space');await page.waitForFunction(()=>nyoroGlide);assert.equal(await page.evaluate(()=>player.jumpsUsed),2);
 const result=await page.evaluate(()=>{
  const check=(v,m)=>{if(!v)throw Error(m);},step=n=>{for(let i=0;i<n;i++)tick(1/120);};
  const setup=(character='denden')=>{selectedCharacter=character;reset();state='playing';pink.enabled=false;player.x=500;platforms=[];crates=[];enemies=[];};
  const enemy=(x)=>{const e={type:'tank',x,y:548,home:x,dir:-1,hp:1000,maxHP:1000,w:62,h:65,flash:0,knock:0,death:-1,range:0,phase:0,stun:100};enemies.push(e);return e;};
  setup();keys.add('KeyD');keys.add('KeyJ');step(1);check(player.vx===CONFIG.walkSpeed*.65,'slower firing movement');keys.clear();bullets=[];player.ammo=1;fire();check(player.reload===1&&bullets.at(-1).bomb,'eighth lightning bomb and one-second reload');const e1=enemy(600),e2=enemy(655);step(10);check(e1.hp===982&&e2.hp===982,'small lightning splash hits both once');check(document.getElementById('ammo').hidden,'reload is above head, HUD hidden');step(110);check(player.ammo===8&&player.reload===0,'one second refill');
  setup();pink.enabled=true;pink.x=250;const roam=enemy(800);step(80);check(pink.x>400,'pink pursues independently');commandPink();check(pink.recall===3&&pink.assist===0,'single tap recalls');step(12);commandPink();check(pink.assist===2&&pink.recall===0,'double tap supports');
  setup('nyoro');check(Object.keys(nyoroFrames).length===46&&nyoroFire.length===5,'all Nyoro images loaded');jumpRequest=.13;step(1);check(player.vy<-750&&player.jumpsUsed===1,'higher first jump');step(15);const before=player.y;jumpRequest=.13;step(1);check(nyoroGlide&&player.vy>=0&&player.jumpsUsed===2,'second jump glides without upward boost');step(60);check(player.y>before&&player.vy<=95&&nyoroShots.length>0,'glide drops small fire');step(500);check(!nyoroGlide&&player.grounded,'landing resets glide');
  setup('nyoro');const target=enemy(580);nyoroAttack();nyoroAttack();step(21);check(target.hp===982,'first melee 18');step(55);check(target.hp<=956&&target.launch&&target.launch.vy<0&&target.burn>0,'queued flame uppercut launches and burns');
  setup('nyoro');castNyoro(0);damagePlayer({x:800},10);check(player.hp===45,'rain damage reduced 50 percent');step(90);check(nyoroAction?.type==='rain'&&nyoroAction.spawned===4,'rain keeps looping while falling');step(40);check(nyoroAction?.spawned===5,'five falling fire groups');step(400);check(!nyoroAction&&!nyoroShots.length,'rain releases player after last impact');
  setup('nyoro');const near=enemy(800),wide=enemy(1000);castNyoro(1);step(115);check(nyoroShots.some(s=>s.kind==='meteor'),'large meteor after five flame positions');step(180);check(near.hp<936&&wide.hp<=936,'large meteor wide damage');
  setup('nyoro');const rider=enemy(540);castNyoro(2);step(115);check(!nyoroSummon,'one-second charge');step(75);check(nyoroSummon&&player.y<440&&rider.y===nyoroSummon.y,'summon lifts player and enemies');check(player.hp===50&&rider.hp<1000,'Nyoro immune, enemy burns');const age=nyoroSummon.age;pause();step(100);check(nyoroSummon.age===age,'summon pauses');resume();step(420);check(!nyoroSummon&&player.grounded&&player.y===548&&rider.y===548,'three second platform ends and riders fall');
  setup('nyoro');castNyoro(2);step(190);selectedCharacter='denden';player.inv=0;step(1);check(player.hp===48,'other character burns on platform');selectedCharacter='nyoro';player.y=950;step(1);check(!nyoroAction&&!nyoroSummon&&!nyoroGlide&&!nyoroShots.length,'fall resets active Nyoro effects');
  setup('nyoro');castNyoro(0);step(30);reset();check(!nyoroAction&&!nyoroShots.length&&nyoroCooldowns.every(c=>c===0),'retry resets new character');
  return {reload:1,shotMove:'.65',bomb:18,nyoro:[18,26,4,24,64],pink:'recall / double tap shield'};
 });console.log(mobile?'MOBILE':'DESKTOP',result);await page.evaluate(()=>{selectedCharacter='nyoro';reset();state='playing';player.x=450;camera=0;castNyoro(2);for(let i=0;i<190;i++)tick(1/120);state='paused';draw();drawSkills();});await page.screenshot({path:path.join(process.env.TEMP,`nyoro-summon-${mobile}.png`)});assert.deepEqual(errors,[]);await context.close();
 }}finally{await browser.close();server.close();}}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
