// npm install --no-save playwright, then: node tests/game.test.cjs
const {chromium}=require('playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png'})[path.extname(file)]||'text/plain'});res.end(e?'Not found':b);});});
async function main(){await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});try{for(const mobile of [false,true]){
 const context=await browser.newContext({viewport:mobile?{width:844,height:390}:{width:1280,height:720},isMobile:mobile,hasTouch:mobile}),page=await context.newPage(),errors=[];page.setDefaultNavigationTimeout(90000);page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>state==='ready');await page.locator('#start').click();
 await page.evaluate(()=>{state='ready';});await page.locator('[data-character="nyoro"]').evaluate(b=>b.click());await page.evaluate(()=>{state='playing';});
 if(mobile)await page.locator('#jump').tap();else await page.keyboard.press('Space');await page.waitForFunction(()=>!player.grounded);if(mobile)await page.locator('#jump').tap();else await page.keyboard.press('Space');await page.waitForFunction(()=>nyoroGlide);assert.equal(await page.evaluate(()=>player.jumpsUsed),2);
 const result=await page.evaluate(()=>{
  const check=(v,m)=>{if(!v)throw Error(m);},step=n=>{for(let i=0;i<n;i++)tick(1/120);};
  const setup=(character='denden')=>{selectedCharacter=character;reset();state='playing';pink.enabled=false;player.x=500;platforms=[];crates=[];enemies=[];};
  const enemy=(x)=>{const e={type:'tank',x,y:548,home:x,dir:-1,hp:1000,maxHP:1000,w:62,h:65,flash:0,knock:0,death:-1,range:0,phase:0,stun:100};enemies.push(e);return e;};
  setup();keys.add('KeyD');keys.add('KeyJ');step(1);check(player.vx===CONFIG.walkSpeed*.65,'slower firing movement');keys.clear();bullets=[];player.ammo=1;fire();check(player.reload===1&&bullets.at(-1).bomb,'eighth lightning bomb and one-second reload');const e1=enemy(600),e2=enemy(655);step(10);check(e1.hp===982&&e2.hp===982,'small lightning splash hits both once');check(document.getElementById('ammo').hidden,'reload is above head, HUD hidden');step(110);check(player.ammo===8&&player.reload===0,'one second refill');
  setup();pink.enabled=true;pink.x=250;const roam=enemy(800);step(80);check(pink.x>400,'pink pursues independently');commandPink();check(pink.recall===3&&pink.assist===0,'single tap recalls');step(12);commandPink();check(pink.assist===2&&pink.recall===0,'double tap supports');
  setup('nyoro');check(Object.keys(nyoroFrames).length===46&&nyoroFire.length===5,'all Nyoro images loaded');jumpRequest=.13;step(1);check(player.vy<-750&&player.jumpsUsed===1,'higher first jump');step(15);const before=player.y;jumpRequest=.13;step(1);check(nyoroGlide&&player.vy>=0&&player.jumpsUsed===2,'second jump glides without upward boost');step(60);check(player.y>before&&player.vy<=95&&nyoroShots.length>0,'glide drops small fire');step(500);check(!nyoroGlide&&player.grounded,'landing resets glide');
  setup('nyoro');const target=enemy(580);nyoroAttack();nyoroAttack();step(21);check(target.hp===982,'first melee 18');step(55);check(target.hp<=956&&target.launch&&target.launch.vy<0&&target.burn>0,'queued flame uppercut launches and burns');
  setup('nyoro');castNyoro(0);damagePlayer({x:800},10);check(player.hp===45,'rain damage reduced 50 percent');step(90);check(nyoroAction?.type==='rain'&&nyoroAction.spawned===4,'rain keeps looping while falling');step(40);check(nyoroAction?.spawned===5,'five falling fire groups');step(400);check(!nyoroAction&&!nyoroShots.length,'rain releases player after last impact');
  setup('nyoro');const near=enemy(800),wide=enemy(940);castNyoro(1);step(115);check(nyoroShots.some(s=>s.kind==='meteor'),'large meteor after five flame positions');step(180);check(near.hp<936&&wide.hp<=936,'large meteor wide damage');
  setup('nyoro');const rider=enemy(540);castNyoro(2);step(115);check(!nyoroSummon,'one-second charge');step(75);check(nyoroSummon&&player.y<440&&Math.abs(rider.y-summonRoofY(rider.x))<1,'summon lifts player and enemies');check(player.hp===50&&rider.hp<1000,'Nyoro immune, enemy burns');const age=nyoroSummon.age;pause();step(100);check(nyoroSummon.age===age,'summon pauses');resume();step(560);check(!nyoroSummon&&player.grounded&&player.y===548&&rider.y===548,'extended platform ends and riders bounce then land');
  setup('nyoro');castNyoro(2);step(190);selectedCharacter='denden';player.inv=0;step(1);check(player.hp===48,'other character burns on platform');selectedCharacter='nyoro';player.y=950;step(1);check(!nyoroAction&&!nyoroSummon&&!nyoroGlide&&!nyoroShots.length,'fall resets active Nyoro effects');
  setup();pink.enabled=true;const start=pink.x;step(12);check(pink.x!==start,'Pink moves from start');
  setup();pink.enabled=true;pink.x=450;player.x=900;gaps=[{x:500,w:500}];bridges=[];crumbles=[];let lowest=0;for(let i=0;i<180;i++){tick(1/120);lowest=Math.max(lowest,pink.y);}check(pink.x<500&&lowest<=550,'Pink waits before an uncrossable hole');
  setup();pink.enabled=true;pink.x=450;player.x=800;gaps=[{x:500,w:100}];bridges=[];crumbles=[];lowest=0;let crossed=false;for(let i=0;i<180;i++){tick(1/120);lowest=Math.max(lowest,pink.y);if(pink.x>610)crossed=true;}check(crossed&&lowest<=550,'Pink jumps to a safe bank '+JSON.stringify({crossed,lowest,pink}));
  setup('nyoro');player.y=260;player.grounded=false;player.coyote=0;player.jumpsUsed=1;jumpRequest=.13;step(1);check(nyoroShots[0].y<0,'glide fire begins in sky');step(80);const vy=player.vy;jumpRequest=.13;step(1);check(player.vy>=vy&&jumpRequest===0,'repeated glide input never resets descent');nyoroAttack();step(54);jumpRequest=.13;step(1);check(!nyoroGlide&&nyoroGlideUsed,'cannot re-glide after cancelling in same jump');
  setup('nyoro');nyoroAttack();step(30);check(player.x>520&&player.x<540,'normal advances');nyoroAction=null;nyoroCombo=.2;nyoroAttack();const upperX=player.x;step(30);check(player.x>upperX+20&&nyoroFX.some(f=>f.kind==='groundWave'),'upper advances with ground wave');
  setup('nyoro');addFire('rain',750,-80,{dir:1});const meteor=nyoroShots[0],mx=meteor.x;step(15);check(meteor.x>mx+25&&meteor.y>-80,'meteor follows diagonal');nyoroShots=[];addFire('meteor',750,-80,{dir:-1});const left=nyoroShots[0],lx=left.x;step(15);check(left.x<lx-25,'left-facing diagonal');
  setup('nyoro');castNyoro(2);step(190);const roof=nyoroSummon;check(Math.abs(summonRoofY(roof.x+30)-summonRoofY(roof.x+120))>70,'roof is shaped, not flat');keys.add('KeyD');step(24);keys.clear();check(Math.abs(player.y-summonRoofY(player.x))<1,'walk follows roof');nyoroSummon.age=3.99;step(2);check(!nyoroSummon&&player.vy<0&&player.jumpsUsed===1,'expiry launches rider and restores glide');jumpRequest=.13;step(1);check(nyoroGlide,'glide after summon bounce');
  setup('nyoro');castNyoro(0);step(30);reset();check(!nyoroAction&&!nyoroShots.length&&nyoroCooldowns.every(c=>c===0),'retry resets new character');
  return {reload:1,shotMove:'.65',bomb:18,nyoro:[18,26,4,24,64],pink:'recall / double tap shield'};
 });console.log(mobile?'MOBILE':'DESKTOP',result);await page.evaluate(()=>{selectedCharacter='nyoro';reset();state='playing';player.x=450;camera=0;castNyoro(2);for(let i=0;i<190;i++)tick(1/120);state='paused';draw();drawSkills();});await page.screenshot({path:path.join(process.env.TEMP,`nyoro-summon-${mobile}.png`)});if(!mobile){const sheet=await page.evaluate(()=>{ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#556878';ctx.fillRect(0,0,1280,720);camera=0;player.inv=0;player.dir=1;for(let n=1;n<=23;n++){if(n>1&&n<9)continue;const i=n===1?0:n-8;player.x=75+(i%8)*155;player.y=180+Math.floor(i/8)*180;nyoroAction=n===1?null:{type:n<17?'normal':'upper',age:(n-(n<17?9:17))*(n<17?.055:.083)+.001};player.vx=0;player.grounded=true;drawNyoro();text(String(n),player.x,player.y+25,16,'white');}ctx.restore();return canvas.toDataURL();});fs.writeFileSync(path.join(process.env.TEMP,'nyoro-body-review.png'),Buffer.from(sheet.split(',')[1],'base64'));}assert.deepEqual(errors,[]);await context.close();
 }}finally{await browser.close();server.close();}}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
