// npm install --no-save playwright, then: node tests/game.test.cjs
const {chromium}=require('playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png'})[path.extname(file)]||'text/plain'});res.end(e?'Not found':b);});});
async function main(){await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});try{for(const mobile of [false,true]){
 const context=await browser.newContext({viewport:mobile?{width:844,height:390}:{width:1280,height:720},isMobile:mobile,hasTouch:mobile}),page=await context.newPage(),errors=[];page.setDefaultNavigationTimeout(90000);page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>state==='ready');await page.locator('#start').click();
 const result=await page.evaluate(()=>{
 const check=(v,m)=>{if(!v)throw Error(m)},step=n=>{for(let i=0;i<n;i++)tick(1/120)};
 const setup=(admin=false)=>{adminUnlocked=admin;selectedCharacter='denden';reset();state='playing';document.getElementById('overlay').hidden=true;enemies=[];crates=[];platforms=[];pink.enabled=false;player.x=800;updateCharacterUI();};
 setup();check(Object.keys(party).length===3&&document.querySelectorAll('.party-slot.ready').length===2,'three-member roster with two glowing switches');
 player.hp=23;check(switchParty('tetsu'),'switch to Tetsu');check(player.hp===50&&party.denden.hp===23&&tetsuAction.type==='air'&&player.y<400,'Tetsu enters from above with jump attack');check(partyEntry.id==='tetsu'&&!switchParty('nyoro'),'global switch cooldown blocks rapid swaps');step(70);check(player.grounded&&worldEffects.some(e=>e.kind==='impact'),'Tetsu lands with impact');
 step(530);check(party.denden.hp===24&&partyCooldown===0,'standby heals one HP in five seconds');check(switchParty('nyoro')&&nyoroGlide&&player.y<500,'Nyoro enters gliding');const x=player.x;step(30);check(player.x>x&&nyoroShots.some(s=>s.kind==='ember'),'entry glide moves and rains fire');
 partyCooldown=0;player.hp=17;check(switchParty('denden'),'switch back');check(player.hp===24&&party.nyoro.hp===17,'individual health preserved');step(60);check(bullets.length>=3&&partyEntry.id==='denden','Denden enters firing');
 const frozen=partyCooldown,regen=party.nyoro.regen;pause();step(600);check(partyCooldown===frozen&&party.nyoro.regen===regen,'pause freezes switch and regen');resume();
 player.hp=1;player.inv=0;damagePlayer({x:player.x+20},100);check(state==='playing'&&party.denden.hp===0&&party.denden.revive===15,'one KO is not game over');step(1);check(selectedCharacter==='tetsu'&&player.hp>0,'KO auto-switch bypasses cooldown');party.nyoro.hp=10;for(let i=0;i<1799;i++)updateParty(1/120);check(party.denden.hp===0&&!switchParty('denden'),'dead member unavailable before fifteen seconds');updateParty(1/120);check(party.denden.hp===1&&party.denden.revive===0,'revive after fifteen seconds at one HP');for(let i=0;i<600;i++)updateParty(1/120);check(party.denden.hp===2,'post-revival standby recovery');
 setup();party.tetsu.hp=0;party.tetsu.revive=15;party.nyoro.hp=0;party.nyoro.revive=15;player.hp=1;player.inv=0;damagePlayer({x:0},100);check(state==='dead','all three down ends immediately');const deadTimer=party.tetsu.revive;step(1800);check(state==='dead'&&party.tetsu.revive===deadTimer,'no revival after game over');
 setup(true);check(Object.keys(party).length===4,'admin unlock adds fourth frame');miraShots.push({kind:'blade',hostile:true});check(switchParty('miramob'),'admin character switch');check(miraAction.type==='skull'&&miraAction.age>=2.2&&miraShots.some(s=>s.hostile),'poison entrance preserves hostile attacks');miraShots=miraShots.filter(s=>!s.hostile);step(1);check(miraShots.some(s=>s.kind==='core'&&!s.hostile),'Mira entry releases poison core');step(125);check(miraEffects.some(s=>s.kind==='skull'),'Mira entry explodes');
 for(const id of ['denden','tetsu','nyoro']){party[id].hp=0;party[id].revive=15;}player.hp=1;player.inv=0;damagePlayer({x:0},100);check(state==='dead','all four down ends admin run');
 setup();skillState.cooldowns=[7,10];player.ammo=2;player.reload=.8;switchParty('nyoro');step(120);partyCooldown=0;switchParty('denden');check(player.ammo===8&&player.reload===0&&skillState.cooldowns[0]>5&&skillState.cooldowns[0]<7,'ammo reload and cooldown persist in reserve');
 bossRoom.state='warping';partyCooldown=0;check(!switchParty('tetsu'),'cinematic cannot be interrupted');bossRoom.state='idle';
 setup();player.hp=10;switchParty('nyoro');player.hp=10;dorayaki.push({x:player.x,y:player.y-20,baseY:player.y-20,age:0,vy:0});updateWorld(0);updateHUD();check(party.nyoro.hp===18&&party.denden.hp===10,'pickup heals active member only');
 setup();return {switchCT:PARTY.switchCooldown,regen:'1 HP / 5s',revive:'15s -> 1 HP',entries:4,gameOver:'whole roster'};
 });console.log(mobile?'MOBILE':'DESKTOP',result);
 const t=page.locator('[data-party="tetsu"]');if(mobile)await t.tap();else await t.click();assert.equal(await page.evaluate(()=>selectedCharacter),'tetsu');await page.evaluate(()=>{state='paused';updateHUD();draw();drawSkills();drawMiraEffects();drawBossRoom();drawPartyEntry();});await page.screenshot({path:path.join(process.env.TEMP,`party-entry-${mobile}.png`)});
 await page.evaluate(()=>{adminUnlocked=true;reset();state='playing';enemies=[];player.x=600;camera=160;party.tetsu.hp=0;party.tetsu.revive=12;party.nyoro.hp=28;updateHUD();state='paused';draw();drawPartyEntry();});await page.screenshot({path:path.join(process.env.TEMP,`party-hud-${mobile}.png`)});assert.deepEqual(errors,[]);await context.close();
 }}finally{await browser.close();server.close();}}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
