const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),server=http.createServer((req,res)=>{const f=path.join(root,decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));fs.readFile(f,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':f.endsWith('.js')?'text/javascript':f.endsWith('.html')?'text/html':f.endsWith('.css')?'text/css':'image/png'});res.end(e?'missing':b);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});try{for(const mobile of [false,true]){const context=await browser.newContext({viewport:mobile?{width:844,height:390}:{width:1280,height:720},isMobile:mobile,hasTouch:mobile}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>state==='ready',null,{timeout:120000});const results=await page.evaluate(()=>{
 const check=(v,m)=>{if(!v)throw Error(m);},maps=[];
 for(let b=0;b<5;b++)for(let a=0;a<4;a++){selectBiome(b);areaIndex=a;reset();state='playing';const allowed=[...BIOME_ENEMIES[b],'dragon','miramob',...(b===1?['sharty']:[])];check(enemies.every(e=>allowed.includes(e.type)),'biome roster '+b+'/'+a);check(BIOME_ENEMIES[b].every(t=>enemies.some(e=>e.type===t)),'both types spawn '+b+'/'+a);check(!!shartyEncounter===(b===1&&a===1),'desert midboss');check(props.length<=3,'obstacle cap');maps.push({b,a,types:[...new Set(enemies.map(e=>e.type))],props:props.length});}
 for(let b=0;b<5;b++){selectBiome(b);areaIndex=3;selectedBoss='miramob';reset();state='playing';bossRoom.state='warping';bossRoom.age=.85;updateBossRoom(.01);bossRoom.state='fighting';bossRoom.spawnClock=0;updateBossRoom(.01);check(enemies.filter(e=>e.bossAdd).every(e=>BIOME_ENEMIES[b].includes(e.type)),'reinforcement roster '+b);check(enemies.some(e=>e.bossAdd),'reinforcement created');}selectedBoss='dragon';
 selectBiome(0);reset();state='playing';pink.enabled=false;enemies=[];platforms=[];props=[];crates=[];gaps=[];player.x=900;player.y=548;player.inv=100;
 const navigation=[];for(const type of ['lime','miira','knife','poison','dancer','kairo','golem']){enemies=[];props=[];crates=[];addGrassProp('rock',450);const e=spawnBiomeEnemy(type,340);e.dir=1;let high=548;for(let i=0;i<420;i++){moveEnemyOnTerrain(e,100,1/120);high=Math.min(high,e.y);}check(e.x>510&&high<455,'jump obstacle '+type+JSON.stringify({x:e.x,y:e.y,high}));navigation.push(type);}
 props=[];crates=[];platforms=[{x:450,y:80,w:120,h:468,solid:true}];const wall=spawnNewEnemy('golem',380);wall.dir=1;for(let i=0;i<180;i++)moveEnemyOnTerrain(wall,100,1/120);check(wall.x<430,'turn at tall wall');platforms=[];
 const actions={tende:['wind'],poison:['dash','jump','claw','orb'],dancer:['flip','dance','step'],kairo:['hop','guard','orb'],golem:['jump','guard','punch','slam']};const combat=[];
 for(const [type,list] of Object.entries(actions)){for(const action of list){enemies=[];newEnemyShots=[];newEnemyFX=[];const e=spawnNewEnemy(type,500);e.stun=0;player.x=760;player.y=548;newEnemyAction(e,action);const x=e.x;let high=e.y;for(let i=0;i<135;i++){updateNewEnemy(e,1/120);high=Math.min(high,e.y);}check(Number.isFinite(e.x)&&Number.isFinite(e.y),'finite action');if(['jump','flip','hop'].includes(action))check(high<(action==='hop'||type==='golem'?475:430),'jump '+type);if(['dash','step'].includes(action))check(e.x>x+50,'dash '+type);if(['wind','orb','dance','slam'].includes(action))check(newEnemyShots.length>0,'projectile '+type+'/'+action);if(action==='guard')check(guardNewEnemy(e,20,-e.dir)<20,'guard '+type);combat.push(type+'/'+action);}
 const frames=newEnemyArt[type+'_defeat'];check(frames.length===16,'16 defeat frames');check(frames[15].h*frames[15].scale<NEW_ENEMIES[type].height*.85,'collapsed silhouette '+type);
 for(const action of NEW_ENEMIES[type].actions){const frames=newEnemyArt[type+'_'+action];check(frames.length===16&&frames.every(f=>f.w>5&&f.h>5&&Number.isFinite(f.scale)),'all isolated frames '+type+'/'+action);}
 }
 newEnemyShots=[];const e=spawnNewEnemy('kairo',500);rosterShot(e,'electric',150,6);player.x=newEnemyShots[0].x+20;player.y=newEnemyShots[0].y+32;player.inv=0;const hp=player.hp;updateNewEnemyProjectiles(.15);check(player.hp<hp,'new projectile damages player');for(let i=0;i<800;i++)updateNewEnemyProjectiles(1/120);check(!newEnemyShots.length&&!newEnemyFX.length,'bounded cleanup');
 for(const type of Object.keys(actions)){enemies=[];const e=spawnNewEnemy(type,500);hitEnemy(e,9999);for(let i=0;i<100;i++)tick(1/120);check(enemies.includes(e),'defeat held '+type);for(let i=0;i<80;i++)tick(1/120);check(!enemies.includes(e),'defeat removed '+type);}
 return{maps,navigation,combat,defeat:true,cleanup:true};});console.log(mobile?'MOBILE':'PC',JSON.stringify(results));
 for(let b=0;b<5;b++){await page.evaluate(b=>{selectBiome(b);areaIndex=0;reset();state='playing';pink.enabled=false;player.x=b===4?1460:1250;player.inv=100;camera=850;document.getElementById('overlay').hidden=true;enemies=[];const e=spawnNewEnemy(['tende','poison','dancer','kairo','golem'][b],b===4?1680:1520);e.stun=0;newEnemyAction(e,['wind','claw','dance','guard','punch'][b]);for(let i=0;i<65;i++)tick(1/120);draw();state='paused';},b);await page.screenshot({path:path.join(root,`tests/roster-${b}-${mobile}.png`)});}
 assert.deepEqual(errors,[]);await context.close();}}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
