// npm install --no-save playwright, then: node tests/game.test.cjs
const {chromium}=require('playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png'})[path.extname(file)]||'text/plain'});res.end(e?'Not found':b);});});
async function main(){await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});try{for(const mobile of [false,true]){
 const context=await browser.newContext({viewport:mobile?{width:844,height:390}:{width:1280,height:720},isMobile:mobile,hasTouch:mobile}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>state==='ready');await page.locator('#start').click();
 if(mobile)await page.locator('[data-skill="0"]').tap();else await page.keyboard.press('1');await page.waitForFunction(()=>skillState.cooldowns[0]>7&&!skillState.charging);
 await page.evaluate(()=>{reset();state='playing';});if(mobile)await page.locator('[data-skill="2"]').tap();else await page.keyboard.press('3');await page.waitForFunction(()=>thunderBursts.length>=2);await page.screenshot({path:path.join(process.env.TEMP,`thunder-bullet-${mobile}.png`)});
 await page.evaluate(()=>{reset();state='playing';});await page.waitForFunction(()=>!document.getElementById('pink-tap').hidden);if(mobile){await page.locator('#pink-tap').tap();await page.locator('#pink-tap').tap();}else await page.locator('#pink-tap').dblclick();assert(await page.evaluate(()=>pink.assist>1.7));await page.screenshot({path:path.join(process.env.TEMP,`pink-help-${mobile}.png`)});
 const result=await page.evaluate(()=>{
  const check=(v,m)=>{if(!v)throw Error(m);},step=n=>{for(let i=0;i<n;i++)tick(1/120);};
  const setup=(character='denden')=>{selectedCharacter=character;reset();state='playing';pink.enabled=false;player.x=500;platforms=[];crates=[];enemies=[];};
  const enemy=(x)=>{const e={type:'tank',x,y:548,home:x,dir:-1,hp:1000,maxHP:1000,w:62,h:65,flash:0,knock:0,death:-1,range:0,phase:0,stun:100};enemies.push(e);return e;};
  setup();beginCharge('tap');endCharge('tap');step(15);check(skillState.charging&&!energyShots.length,'short automatic charge');const age=skillState.charge;pause();step(60);check(skillState.charge===age,'auto charge pauses');resume();step(16);check(!skillState.charging&&energyShots.length===1&&energyShots[0].damage===120,'auto fires max power');beginCharge('blocked');check(!skillState.charging,'cooldown blocks repeat');
  setup();const direct=enemy(680),splash=enemy(880);beginCharge('tap');step(48);check(direct.hp===880&&splash.hp===928,'120 direct, 72 wide splash');check(explosions.length===1&&explosions[0].r===260,'large bubble explosion');step(100);check(!energyShots.length&&!explosions.length,'bubble cleanup');
  setup();const targets=[enemy(595),enemy(725),enemy(895)];castThunderBullet();step(28);check(thunderBursts.length===0,'wait until shot');step(3);check(thunderBursts.length===1,'first burst');step(16);check(thunderBursts.length===2,'second burst');step(17);check(thunderBursts.length===3&&thunderBursts[0].size<thunderBursts[1].size&&thunderBursts[1].size<thunderBursts[2].size,'three increasing sizes');check(targets.every(e=>e.hp<1000&&e.launch?.spin===17&&e.electric>0),'electric spinning launch');const cd=thunderBulletCooldown;castThunderBullet();check(thunderBulletCooldown===cd,'no skill3 recast');step(100);check(!thunderBullet&&!thunderBursts.length,'skill3 cleanup');
  setup();player.dir=-1;castThunderBullet();step(64);check(thunderBursts.map(b=>b.x).join(',')==='405,275,105','leftward sequence');
  setup('tetsu');let e=enemy(615);startTetsuAction('normal');step(37);check(!tetsuAction&&player.x>540&&e.hp===982,'faster advancing normal and reach');
  setup('tetsu');e=enemy(625);startTetsuAction('combo');step(22);check(e.hp===988,'earlier combo mid hit');step(75);check(e.hp===972&&!tetsuAction&&player.x>570,'faster advancing two-hit combo');
  setup('tetsu');player.inv=0;startTetsuAction('normal');damagePlayer({type:'tank',x:600},10);check(player.hp===45,'50 percent motion reduction');tetsuAction=null;player.inv=0;damagePlayer({type:'tank',x:600},10);check(player.hp===35,'normal damage outside action');
  setup('tetsu');e=enemy(570);e.stun=0;e.type='miira';e.attackAge=.3;e.attackCooldown=0;castTetsu(2);step(100);check(e.stun>0&&e.x===570&&!dirtBalls.length&&e.hp===1000,'charge stuns, stops throw, no early damage');
  setup();pink.enabled=true;pink.x=435;pink.y=548;axis=1;step(80);check(pink.x<player.x&&player.x-pink.x>150&&player.x-pink.x<400,'looser dash follow');axis=0;jumpRequest=CONFIG.jumpBuffer;step(1);check(!pink.grounded&&pink.vy<0,'mirrored jump');
  setup();pink.enabled=true;pink.x=435;e=enemy(510);player.inv=100;step(75);check(e.hp===990&&pink.attack===null,'autonomous shield attack');
  setup();pink.enabled=true;pink.x=435;activatePink();player.x=435;player.y=435;player.vy=200;player.grounded=false;step(20);check(player.vy< -800&&player.y<464,'shield trampoline bounce');const remaining=pink.assist;pause();step(60);check(pink.assist===remaining,'support pauses');resume();step(260);check(pink.assist===0,'support lasts two seconds');
  setup();const a=arenas[0];player.x=a.x+200;player.inv=100;step(120);check(enemies.some(e=>e.dropping)&&a.spawned>=6,'crowd spawns from above');let drops=0;for(let i=0;i<2400&&a.state!=='cleared';i++){for(const e of enemies){if(e.dropping)drops++;hitEnemy(e,1000);}tick(1/120);}check(a.state==='cleared'&&a.spawned===48&&drops>0,'all 48 required before unlock');
  reset();check(pink.enabled&&pink.assist===0&&!thunderBullet&&!thunderBursts.length&&thunderBulletCooldown===0,'retry resets support and new skill');
  return {autoCharge:.25,bubble:[120,72,260],thunder:[36,48,60],pinkDamage:10,arena:48,reduction:'50%'};
 });console.log(mobile?'MOBILE':'DESKTOP',result);assert.deepEqual(errors,[]);await context.close();
 }}finally{await browser.close();server.close();}}
main().catch(e=>{console.error(e);server.close();process.exitCode=1;});
